### ISSUE TITLE
[Windows] The application crashes when started from location containing exclamation mark (!)

### ISSUE THREAD

**Issue by PeterWolfKe** [ribomation/DroidAtScreen1#32]
I moved the JAR file to folder named "!".
file:/C:/Users/Peter/Downloads/!/droidAtScreen-1.2.jar
Then I wasn't able to run the application. It still works from this location:
file:/C:/Users/Peter/Downloads/droidAtScreen-1.2.jar

The console output was:
```
log4j:ERROR Could not read configuration file from URL [jar:file:/C:/Users/Peter/Downloads/!/droidAtScreen-1.2.jar!/log4j.properties].
java.io.FileNotFoundException: C:\Users\Peter\Downloads (Access denied)
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.jar.JarFile.<init>(Unknown Source)
        at java.util.jar.JarFile.<init>(Unknown Source)
        at sun.net.www.protocol.jar.URLJarFile.<init>(Unknown Source)
        at sun.net.www.protocol.jar.URLJarFile.getJarFile(Unknown Source)
        at sun.net.www.protocol.jar.JarFileFactory.get(Unknown Source)
        at sun.net.www.protocol.jar.JarURLConnection.connect(Unknown Source)
        at sun.net.www.protocol.jar.JarURLConnection.getInputStream(Unknown Source)
        at java.net.URL.openStream(Unknown Source)
        at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:433)
        at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:470)
        at org.apache.log4j.LogManager.<clinit>(LogManager.java:122)
        at org.apache.log4j.Logger.getLogger(Logger.java:117)
        at com.ribomation.droidAtScreen.DroidAtScreenApplication.<init>(DroidAtScreenApplication.java:49)
        at com.ribomation.droidAtScreen.DroidAtScreenApplication.main(DroidAtScreenApplication.java:59)
log4j:ERROR Ignoring configuration file [jar:file:/C:/Users/Peter/Downloads/!/droidAtScreen-1.2.jar!/log4j.properties].
log4j:WARN No appenders could be found for logger (com.ribomation.droidAtScreen.DroidAtScreenApplication).
log4j:WARN Please initialize the log4j system properly.
Exception in thread "main" java.lang.NullPointerException
        at com.ribomation.droidAtScreen.DroidAtScreenApplication$1.getName(DroidAtScreenApplication.java:208)
        at com.ribomation.droidAtScreen.gui.ApplicationFrame.initGUI(ApplicationFrame.java:63)
        at com.ribomation.droidAtScreen.DroidAtScreenApplication.initGUI(DroidAtScreenApplication.java:104)
        at com.ribomation.droidAtScreen.DroidAtScreenApplication.main(DroidAtScreenApplication.java:63)
```

**Comment by ribomation** [comment]
Looks like a JVM launcher problem. Bring it up with Oracle.
