### ISSUE TITLE
Unable to see any devices - NullPointerException when reloading

### ISSUE THREAD

**Issue by duckinferno** [ribomation/DroidAtScreen1#34]
Hi, versions 1.1 and 1.2 do not allow me to see any devices or restart adb.  I have tried relying on my ANDROID_HOME env variable and manually entering the path to it, neither helps.  I develop on this pc + phone and can confirm that the SDK, ADB etc are set up correctly.

The following exception displays when I attempt to either restart adb or reload devices.

```
▶ java -jar ~/Downloads/droidAtScreen-1.1.jar
2017-01-13 08:57:46,053 DEBUG DroidAtScreenApplication - parseArgs: []
2017-01-13 08:57:46,054 DEBUG DroidAtScreenApplication - initProperties
2017-01-13 08:57:46,061 DEBUG Settings - --- Application Settings ---
2017-01-13 08:57:46,062 DEBUG DroidAtScreenApplication - initCommands
2017-01-13 08:57:46,064 DEBUG DroidAtScreenApplication - initGUI
2017-01-13 08:57:47,428 DEBUG DroidAtScreenApplication - initAndroid
2017-01-13 08:57:47,445 DEBUG DroidAtScreenApplication - run
2017-01-13 08:57:47,480 DEBUG DroidAtScreenApplication - postStart
2017-01-13 08:57:47,480 DEBUG DroidAtScreenApplication - isExe: env=null
2017-01-13 08:57:47,481 DEBUG DroidAtScreenApplication - isExe: env=null
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at com.ribomation.droidAtScreen.dev.AndroidDeviceManager.reloadDevices(AndroidDeviceManager.java:115)
	at com.ribomation.droidAtScreen.cmd.AdbReloadDevicesCommand$1.run(AdbReloadDevicesCommand.java:40)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at com.ribomation.droidAtScreen.dev.AndroidDeviceManager.restartADB(AndroidDeviceManager.java:121)
	at com.ribomation.droidAtScreen.cmd.AdbRestartCommand$1.run(AdbRestartCommand.java:44)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Phone: Google Pixel w/ Android 7.1.1
PC: MBP w/ macOS Sierra 10.12

**Comment by noraj1337** [comment]
Exactly the same error.

```
$ adb --version
Android Debug Bridge version 1.0.36
Revision 7.1.1_r13
```
Phone: Elephone P7000 / Android 5.0 / Kernel 3.10.61
PC : Manjaro (ArchLinux) Kernel 4.9.24-1

**Comment by homotopycolimit** [comment]
same error for me.

```
Exception in thread "AWT-EventQueue-1" java.lang.NullPointerException
	at com.ribomation.droidAtScreen.dev.AndroidDeviceManager.reloadDevices(AndroidDeviceManager.java:115)
	at com.ribomation.droidAtScreen.cmd.AdbReloadDevicesCommand$1.run(AdbReloadDevicesCommand.java:40)
```
and so on.

**Comment by MedicMomcilo** [comment]
When running on Linux, this usually means you're either trying to use it without platform tools, or superuser privileges.
